name: PR Test
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
concurrency:
  group: pr-test-${{ github.event.pull_request.html_url }}
  cancel-in-progress: true
env:
  NODE_OPTIONS: --max-old-space-size=4096
jobs:
  pre-run:
    if: github.event.pull_request.draft == false && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      pr-tests: ${{ steps.out-step.outputs.pr-tests }}
    steps:
      - uses: actions/checkout@v4

      # Extract PR Tests from pull request body
      - name: Check for PR Tests
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match-pr-tests
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '### PR Tests[\\s\\S]*?```([\\s\\S]*?)```'
          flags: m

      - name: Pass PR Tests to run job
        id: out-step
        run: |
          CONTENT="${{ steps.regex-match-pr-tests.outputs.group1 }}"
          if [ -n "$CONTENT" ]; then
            {
              echo 'pr-tests<<__PR_TESTS__'
              printf '%s' "$CONTENT"
              echo
              echo '__PR_TESTS__'
            } >> "$GITHUB_OUTPUT"
          fi

  run-tests:
    needs: pre-run
    if: needs.pre-run.outputs.pr-tests != ''
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Enable corepack and setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.6.7 --activate

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install --store-dir=node_modules/.pnpm-store

      - name: Run tests from PR description
        run: node ./scripts/ci/test-pr.js
        env:
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          NO_COLOR: 1

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            coverage/**
            playwright-report/**
            test-results/**
